---
- name: collect logs
  hosts: all
  become: yes
  tasks:
    - name: copy current boot logs to file
      shell: "journalctl -b 0 > /tmp/journalctl"
    - name: Compress log file
      archive:
        path: /tmp/journalctl
        dest: /tmp/journalctl.tar.bz2
        format: bz2
        remove: true
        force_archive: true
     -name: Copy log archive to controller
      fetch:
        src: /tmp/journalctl.tar.bz2
        dest: "/home/demiadmin/Demirep/logs/journalctl-{{ ansible_hostname }}.tar.bz2"
        flat: true

